# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestSun < Formula
  desc "Best Tesseract OCR data for Sundanese (sun)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/sun.traineddata"
  sha256 "a9fc58f3868c7e88c4791078090a7f7436b01cc45cd660f7b756a0e0683b5a5c"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "sun.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/sun.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l sun
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/sun.traineddata"
  end
end
