# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestIta < Formula
  desc "Best Tesseract OCR data for Italian (ita)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/ita.traineddata"
  sha256 "8df9c89176fb93f56bf4b2d4ede04c01c1f31d4b7697fbd76cc336df700f3f38"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "ita.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/ita.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l ita
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/ita.traineddata"
  end
end
