# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestGla < Formula
  desc "Best Tesseract OCR data for Scottish Gaelic (gla)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/gla.traineddata"
  sha256 "b0c35f0b10ff45735d2c488c8cab8fb6fc56631c8a7e38f8210e1dff05b34f8d"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "gla.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/gla.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l gla
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/gla.traineddata"
  end
end
