# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestAmh < Formula
  desc "Best Tesseract OCR data for Amharic (amh)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/amh.traineddata"
  sha256 "e29d8041115f924c8fb0ad11c42034fa0f5d76cd974903b56816e06e73767974"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "amh.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/amh.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l amh
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/amh.traineddata"
  end
end
