# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestMon < Formula
  desc "Best Tesseract OCR data for Mongolian (mon)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/mon.traineddata"
  sha256 "186dcb2ef79e0dc1ab88da2231926d79070c20176bf7416a19389331f68faf65"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "mon.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/mon.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l mon
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/mon.traineddata"
  end
end
