# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestUzbCyrl < Formula
  desc "Best Tesseract OCR data for Uzbek (Cyrillic) (uzb_cyrl)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/uzb_cyrl.traineddata"
  sha256 "13b5f943418d362ed2a445c43777e9244ab70359bcc31a95eb89738ccd6924b1"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "uzb_cyrl.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/uzb_cyrl.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l uzb_cyrl
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/uzb_cyrl.traineddata"
  end
end
