# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestOci < Formula
  desc "Best Tesseract OCR data for Occitan (oci)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/oci.traineddata"
  sha256 "623733a34bb8923e8806701d324c6c021f949debf233fe98bfd58f9b6939fe2d"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "oci.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/oci.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l oci
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/oci.traineddata"
  end
end
