# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptCanadianAboriginal < Formula
  desc "Best Tesseract OCR script data for Canadian Aboriginal"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Canadian_Aboriginal.traineddata"
  sha256 "f2ece862f3a6e6fa6bb41e2100d5425ad19c6c72b716277ca2ecb78c57e2f9b3"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Canadian_Aboriginal.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Canadian_Aboriginal.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Canadian_Aboriginal
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Canadian_Aboriginal.traineddata"
  end
end
