# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestGlg < Formula
  desc "Best Tesseract OCR data for Galician (glg)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/glg.traineddata"
  sha256 "bfe93fafb41a44e9efd612c6f9833f8a7f76a157824d933420116f5aa3439463"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "glg.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/glg.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l glg
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/glg.traineddata"
  end
end
