# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestKmr < Formula
  desc "Best Tesseract OCR data for Northern Kurdish (kmr)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/kmr.traineddata"
  sha256 "6017f6284e6771419f85a72218a2e84c5c6c19a4ed0ef27286cd637981293b76"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "kmr.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/kmr.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l kmr
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/kmr.traineddata"
  end
end
