# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptTamil < Formula
  desc "Best Tesseract OCR script data for Tamil"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Tamil.traineddata"
  sha256 "056a2bd2dd2e23d64a5f00f420324bc101206562b93a93ca1c057ce9ad68ef9e"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Tamil.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Tamil.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Tamil
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Tamil.traineddata"
  end
end
