# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestMlt < Formula
  desc "Best Tesseract OCR data for Maltese (mlt)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/mlt.traineddata"
  sha256 "0408941b9368de0009c530b68f0adc4735d6c26bfa02e549d0ee48afc776f0a4"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "mlt.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/mlt.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l mlt
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/mlt.traineddata"
  end
end
