# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestKatOld < Formula
  desc "Best Tesseract OCR data for Georgian (Old) (kat_old)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/kat_old.traineddata"
  sha256 "ada8c6b31828d2e208312e6d28b92fd94cb924f48f676506d3592cf023bb487d"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "kat_old.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/kat_old.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l kat_old
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/kat_old.traineddata"
  end
end
