# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptHansVert < Formula
  desc "Best Tesseract OCR script data for Han Simplified (Vertical)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/HanS_vert.traineddata"
  sha256 "1ed0f838b85935d17a94a7ac6ca0194dc0cc099e9e6ce7112246ae7ab56b5b73"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "HanS_vert.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/HanS_vert.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/HanS_vert
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/HanS_vert.traineddata"
  end
end
