# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestLat < Formula
  desc "Best Tesseract OCR data for Latin (lat)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/lat.traineddata"
  sha256 "60054dd32ac03ebd9b4f87d0665bd491a7ffe0d3ee99ceb91aefaf348b65e94f"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "lat.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/lat.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l lat
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/lat.traineddata"
  end
end
