# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptHebrew < Formula
  desc "Best Tesseract OCR script data for Hebrew"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Hebrew.traineddata"
  sha256 "656090bce4c45eedef9e5f9adde04a42d7a146ba37d39d88936f34a88628bcc6"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Hebrew.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Hebrew.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Hebrew
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Hebrew.traineddata"
  end
end
