# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptDevanagari < Formula
  desc "Best Tesseract OCR script data for Devanagari"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Devanagari.traineddata"
  sha256 "7ffe34c3cf6d512d2713a83c1f7ca580ae19e2e17d2b71c3f70e225652f907ce"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Devanagari.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Devanagari.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Devanagari
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Devanagari.traineddata"
  end
end
