# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestUzb < Formula
  desc "Best Tesseract OCR data for Uzbek (uzb)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/uzb.traineddata"
  sha256 "5bd8a1958b3cee68aa225774b89775f3a510dd2141e7d9eb2b5931adca2624c8"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "uzb.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/uzb.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l uzb
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/uzb.traineddata"
  end
end
