# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestVie < Formula
  desc "Best Tesseract OCR data for Vietnamese (vie)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/vie.traineddata"
  sha256 "b6b49293d95d0b6dbd8780174627e82c75be957b6f4ed9862155540d6b00bb45"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "vie.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/vie.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l vie
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/vie.traineddata"
  end
end
