# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestRus < Formula
  desc "Best Tesseract OCR data for Russian (rus)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/rus.traineddata"
  sha256 "b617eb6830ffabaaa795dd87ea7fd251adfe9cf0efe05eb9a2e8128b7728d6b6"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "rus.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/rus.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l rus
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/rus.traineddata"
  end
end
