# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestLao < Formula
  desc "Best Tesseract OCR data for Lao (lao)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/lao.traineddata"
  sha256 "12680f24af571909d69f0dd0151ecdf657a98f000c0ca011c11f8f9dc2bf69b7"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "lao.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/lao.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l lao
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/lao.traineddata"
  end
end
