# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestSqi < Formula
  desc "Best Tesseract OCR data for Albanian (sqi)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/sqi.traineddata"
  sha256 "42fa3ff84e1684b8989423d53c9f7d4fb8adaa65a54a3d87f9d259228d01226c"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "sqi.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/sqi.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l sqi
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/sqi.traineddata"
  end
end
