# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestKhm < Formula
  desc "Best Tesseract OCR data for Khmer (khm)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/khm.traineddata"
  sha256 "3d2d975e67a319bf1cd67626b12fdebc1e417a4ebef9c9afee01d9927b512815"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "khm.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/khm.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l khm
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/khm.traineddata"
  end
end
