# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestEpo < Formula
  desc "Best Tesseract OCR data for Esperanto (epo)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/epo.traineddata"
  sha256 "43b6b859a59e26b5787962e100fdd16999b2af918f10ca62bcc3f7d2f9744365"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "epo.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/epo.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l epo
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/epo.traineddata"
  end
end
