# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestKorVert < Formula
  desc "Best Tesseract OCR data for Korean (Vertical) (kor_vert)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/kor_vert.traineddata"
  sha256 "e6c72327617c0bf195a9a8b631827bf102c75735bbb932126e6fa1c4656c7568"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "kor_vert.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/kor_vert.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l kor_vert
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/kor_vert.traineddata"
  end
end
