# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptGurmukhi < Formula
  desc "Best Tesseract OCR script data for Gurmukhi"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Gurmukhi.traineddata"
  sha256 "30d164129956fb4c1b81b6dc32233c87ff313c81efca706d444a617950641c23"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Gurmukhi.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Gurmukhi.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Gurmukhi
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Gurmukhi.traineddata"
  end
end
