# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptHant < Formula
  desc "Best Tesseract OCR script data for Han Traditional"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/HanT.traineddata"
  sha256 "0de8b33fce2b03ef78ecc5ea4f5c699a218e4445bd05d532d305faa9f749e3cb"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "HanT.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/HanT.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/HanT
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/HanT.traineddata"
  end
end
