# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestSrpLatn < Formula
  desc "Best Tesseract OCR data for Serbian (Latin) (srp_latn)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/srp_latn.traineddata"
  sha256 "9bc6caa2ad9daf1706bf4c21741992dd5a334e9ff64cfc1ecd32aa43dd7a150c"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "srp_latn.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/srp_latn.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l srp_latn
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/srp_latn.traineddata"
  end
end
