# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestEus < Formula
  desc "Best Tesseract OCR data for Basque (eus)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/eus.traineddata"
  sha256 "cd2d5452b6cc704924e5a0a31667dc5cb9f16d4e5cf7cb0629af3781086af7dd"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "eus.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/eus.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l eus
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/eus.traineddata"
  end
end
