# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptArmenian < Formula
  desc "Best Tesseract OCR script data for Armenian"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Armenian.traineddata"
  sha256 "ad63352965602f19aa88e5aae0ae66332cef0e338954ff1d0f53812b719459db"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Armenian.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Armenian.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Armenian
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Armenian.traineddata"
  end
end
