# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestLit < Formula
  desc "Best Tesseract OCR data for Lithuanian (lit)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/lit.traineddata"
  sha256 "7d47a118f60509408e1dae2dd967d7c553a770e57390fedf8e7af07a192fefe3"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "lit.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/lit.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l lit
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/lit.traineddata"
  end
end
