# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestDan < Formula
  desc "Best Tesseract OCR data for Danish (dan)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/dan.traineddata"
  sha256 "28901bf4b58a657b511fddafce4ce245a1f21c5ee075734b479d01ab8d4cb6a5"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "dan.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/dan.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l dan
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/dan.traineddata"
  end
end
