# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestGuj < Formula
  desc "Best Tesseract OCR data for Gujarati (guj)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/guj.traineddata"
  sha256 "8cbb1d139b63434b9e1154a3b51930a74ec1c9a6251b95d86d74d7f1cd706ed6"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "guj.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/guj.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l guj
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/guj.traineddata"
  end
end
