# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestItaOld < Formula
  desc "Best Tesseract OCR data for Italian (Old) (ita_old)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/ita_old.traineddata"
  sha256 "6bba512704bc5417462435f7c98f6b2be86457d544bbb09c7f9ab5caef955b5d"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "ita_old.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/ita_old.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l ita_old
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/ita_old.traineddata"
  end
end
