# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptKhmer < Formula
  desc "Best Tesseract OCR script data for Khmer"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Khmer.traineddata"
  sha256 "a33d31337dc43523673053eab9d60806aedb6601409601ec2273969367494739"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Khmer.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Khmer.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Khmer
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Khmer.traineddata"
  end
end
