# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestLtz < Formula
  desc "Best Tesseract OCR data for Luxembourgish (ltz)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/ltz.traineddata"
  sha256 "cc62ddc05eaa70e1ff0135a428b1ef553f3abd2e5f4485ca084a1980e251a3e1"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "ltz.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/ltz.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l ltz
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/ltz.traineddata"
  end
end
