# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestCes < Formula
  desc "Best Tesseract OCR data for Czech (ces)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/ces.traineddata"
  sha256 "d821773116d3c4e0360ea750066436c60ae45af02c39da3a840a543d761b3f41"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "ces.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/ces.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l ces
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/ces.traineddata"
  end
end
