# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptMyanmar < Formula
  desc "Best Tesseract OCR script data for Myanmar"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Myanmar.traineddata"
  sha256 "c02833fe1c7abffe4a208d88ef7e1b503bdff816ae050151599e78bb6ec9ac42"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Myanmar.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Myanmar.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Myanmar
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Myanmar.traineddata"
  end
end
