# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestTon < Formula
  desc "Best Tesseract OCR data for Tongan (ton)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/ton.traineddata"
  sha256 "64ba54baada51100cc5cb79d42b644dd6bfcdcf5f1efe76c2c53db5d3acb89c2"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "ton.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/ton.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l ton
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/ton.traineddata"
  end
end
