# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestTat < Formula
  desc "Best Tesseract OCR data for Tatar (tat)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/tat.traineddata"
  sha256 "615a1d0d8b9f5c235cc6b4d3d94801371ddfdd9d63114a578c149dc1515d091a"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "tat.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/tat.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l tat
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/tat.traineddata"
  end
end
