# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestPor < Formula
  desc "Best Tesseract OCR data for Portuguese (por)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/por.traineddata"
  sha256 "711de9dbb8052067bd42f16b9119967f30bada80d57e2ef24f65d09f531adb04"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "por.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/por.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l por
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/por.traineddata"
  end
end
