# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptSinhala < Formula
  desc "Best Tesseract OCR script data for Sinhala"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Sinhala.traineddata"
  sha256 "890d85d5f705e2023b848b5f9ef8f2da8314b31132a1d4978f37da658b8429b7"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Sinhala.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Sinhala.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Sinhala
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Sinhala.traineddata"
  end
end
