# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestSlk < Formula
  desc "Best Tesseract OCR data for Slovak (slk)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/slk.traineddata"
  sha256 "3553e335f64408412c8741fec19e443b5fda81d88abe59aa1401cba4e8825bed"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "slk.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/slk.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l slk
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/slk.traineddata"
  end
end
