# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestSwa < Formula
  desc "Best Tesseract OCR data for Swahili (swa)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/swa.traineddata"
  sha256 "102ebfc90724b4aebfab5bad0447ab124b7e2e82877b24895b31b0009e6fd0e0"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "swa.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/swa.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l swa
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/swa.traineddata"
  end
end
