# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestHeb < Formula
  desc "Best Tesseract OCR data for Hebrew (heb)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/heb.traineddata"
  sha256 "dbaa827aea6bc21215638447f17783a1004987c2d0bf5573d111fee397abdae5"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "heb.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/heb.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l heb
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/heb.traineddata"
  end
end
