# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptMalayalam < Formula
  desc "Best Tesseract OCR script data for Malayalam"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Malayalam.traineddata"
  sha256 "4fdd52e34bf8a00e00deeadc93dd3f90539739bd565867e3db62f3bdfd057629"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Malayalam.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Malayalam.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Malayalam
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Malayalam.traineddata"
  end
end
