# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptOriya < Formula
  desc "Best Tesseract OCR script data for Oriya"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Oriya.traineddata"
  sha256 "beafed2d6bff8c0c86d87c18308928924ffd7b2eec96cc4ffdf731c321494187"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Oriya.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Oriya.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Oriya
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Oriya.traineddata"
  end
end
