# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestTam < Formula
  desc "Best Tesseract OCR data for Tamil (tam)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/tam.traineddata"
  sha256 "4b9ce85987f629dd31eaf87443a1646452a43cdf91fcf05e017382ad595dcb9e"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "tam.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/tam.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l tam
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/tam.traineddata"
  end
end
