# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestMal < Formula
  desc "Best Tesseract OCR data for Malayalam (mal)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/mal.traineddata"
  sha256 "b4a8b1b2fd8c5754aa0f543568626aad514d94a6c1e138ef0bf1a329aa189ef0"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "mal.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/mal.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l mal
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/mal.traineddata"
  end
end
