# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestHat < Formula
  desc "Best Tesseract OCR data for Haitian Creole (hat)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/hat.traineddata"
  sha256 "37a2d94a952649da9c8bd18ed3ab4e7c91250656027751f6ccf75a3d8b7457e8"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "hat.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/hat.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l hat
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/hat.traineddata"
  end
end
