# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestMar < Formula
  desc "Best Tesseract OCR data for Marathi (mar)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/mar.traineddata"
  sha256 "799405456528ffd688bc8173ea9179c0646120436ac35099dccb175c4c70f652"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "mar.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/mar.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l mar
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/mar.traineddata"
  end
end
