# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestOsd < Formula
  desc "Best Tesseract OCR data for Orientation/Script Detection (osd)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/osd.traineddata"
  sha256 "9cf5d576fcc47564f11265841e5ca839001e7e6f38ff7f7aacf46d15a96b00ff"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "osd.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/osd.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l osd
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/osd.traineddata"
  end
end
