# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestKor < Formula
  desc "Best Tesseract OCR data for Korean (kor)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/kor.traineddata"
  sha256 "f888d4038348a0c3d25151e7f452bda0d74ca275b18cab146798bcbb94084fff"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "kor.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/kor.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l kor
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/kor.traineddata"
  end
end
