# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestFrk < Formula
  desc "Best Tesseract OCR data for German (Fraktur) (frk)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/frk.traineddata"
  sha256 "429b8c33d37e1a4823a2bb082a644ff13e252f735b7945e08a518d22ddcc459e"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "frk.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/frk.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l frk
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/frk.traineddata"
  end
end
