# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestBre < Formula
  desc "Best Tesseract OCR data for Breton (bre)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/bre.traineddata"
  sha256 "18f11e71bafe0b6170531dd9910ed20ae72dc3750c335d15199ea51ccf029c27"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "bre.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/bre.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l bre
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/bre.traineddata"
  end
end
