# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptFraktur < Formula
  desc "Best Tesseract OCR script data for Fraktur"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Fraktur.traineddata"
  sha256 "29a867a25f1b00a5e9827356582515619d5102688bc1d14015789c78941116ee"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Fraktur.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Fraktur.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Fraktur
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Fraktur.traineddata"
  end
end
