# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestNep < Formula
  desc "Best Tesseract OCR data for Nepali (nep)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/nep.traineddata"
  sha256 "54907633d05bb9fae7dbfb3d8a61ddf2f579127375aa53b8afc657efb34a79f0"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "nep.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/nep.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l nep
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/nep.traineddata"
  end
end
