# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestCos < Formula
  desc "Best Tesseract OCR data for Corsican (cos)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/cos.traineddata"
  sha256 "eb30628f7babafcb55286f9a181f80a5d20fab6dacd1fcde376fd9550f855659"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "cos.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/cos.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l cos
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/cos.traineddata"
  end
end
