# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestFrm < Formula
  desc "Best Tesseract OCR data for French (Middle) (frm)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/frm.traineddata"
  sha256 "72c2de7476d9800a4a12c3d1b9e8c3c211fb76ff9793f4cf453bba8d0672eb77"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "frm.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/frm.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l frm
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/frm.traineddata"
  end
end
