# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptCherokee < Formula
  desc "Best Tesseract OCR script data for Cherokee"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Cherokee.traineddata"
  sha256 "1c305877403345754fefa5e7355265d5b5a2ca2722b9a39064ae259bb6c2e0cc"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Cherokee.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Cherokee.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Cherokee
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Cherokee.traineddata"
  end
end
