# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestQue < Formula
  desc "Best Tesseract OCR data for Quechua (que)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/que.traineddata"
  sha256 "fe8872e0360ecedd40c9df8585fa853a2d82b99a8daa454892ddf9db12fe9135"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "que.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/que.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l que
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/que.traineddata"
  end
end
