# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestSan < Formula
  desc "Best Tesseract OCR data for Sanskrit (san)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/san.traineddata"
  sha256 "5fbc152e7946b3b8201a2a557864bd23b521db4102b521f3e95169c82c5d0b0d"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "san.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/san.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l san
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/san.traineddata"
  end
end
