# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestFil < Formula
  desc "Best Tesseract OCR data for Filipino (fil)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/fil.traineddata"
  sha256 "04a7d20dcd2e1869375cbf47b59d8ed4ceea98c7f01706269eced3945b763647"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "fil.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/fil.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l fil
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/fil.traineddata"
  end
end
