# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptTelugu < Formula
  desc "Best Tesseract OCR script data for Telugu"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Telugu.traineddata"
  sha256 "3539c308308ce29524e456b3fded2fc5a61de62d8e5a9ecee0cd7578019dcb9f"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Telugu.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Telugu.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Telugu
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Telugu.traineddata"
  end
end
