# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestJav < Formula
  desc "Best Tesseract OCR data for Javanese (jav)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/jav.traineddata"
  sha256 "914fe51f967efa4f05b72a852b2c234af3cdd4aefc0f64d43e39903d2108017a"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "jav.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/jav.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l jav
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/jav.traineddata"
  end
end
