# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptGreek < Formula
  desc "Best Tesseract OCR script data for Greek"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Greek.traineddata"
  sha256 "1f527aef281c95c94112f8e698c87a335d82157e9e6183309ee39bcf75b6785b"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Greek.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Greek.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Greek
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Greek.traineddata"
  end
end
