# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestKir < Formula
  desc "Best Tesseract OCR data for Kyrgyz (kir)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/kir.traineddata"
  sha256 "607cbaa07305217518df0e9c7334239000a8542689baefb3754e0aee15ae6a5c"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "kir.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/kir.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l kir
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/kir.traineddata"
  end
end
