# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptThai < Formula
  desc "Best Tesseract OCR script data for Thai"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Thai.traineddata"
  sha256 "e3d1f0c68b47baffec4f7f4abb885c26757ad20e81436a6e369f12483a22a41b"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Thai.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Thai.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Thai
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Thai.traineddata"
  end
end
