# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptKannada < Formula
  desc "Best Tesseract OCR script data for Kannada"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Kannada.traineddata"
  sha256 "906d666cc1b257d5d9d3854608435d1a6b7941ccd0f8ee4e51b181ed7a0a0c13"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Kannada.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Kannada.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Kannada
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Kannada.traineddata"
  end
end
