# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestSpaOld < Formula
  desc "Best Tesseract OCR data for Spanish (Old) (spa_old)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/spa_old.traineddata"
  sha256 "82eda2ae145ce6560e34f8b7b037707bbd7dca109151a50e3356e2fa2ae635e8"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "spa_old.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/spa_old.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l spa_old
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/spa_old.traineddata"
  end
end
