# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptJapaneseVert < Formula
  desc "Best Tesseract OCR script data for Japanese (Vertical)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Japanese_vert.traineddata"
  sha256 "6eca729ad647326a2149e09cf0589d626f4e746863092e22f46841eae4574a49"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Japanese_vert.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Japanese_vert.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Japanese_vert
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Japanese_vert.traineddata"
  end
end
