# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestSlv < Formula
  desc "Best Tesseract OCR data for Slovenian (slv)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/slv.traineddata"
  sha256 "199c39cc570812db5011ad7e8552c04b0784413043a8e4561d85c8ac364fba5c"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "slv.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/slv.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l slv
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/slv.traineddata"
  end
end
