# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptArabic < Formula
  desc "Best Tesseract OCR script data for Arabic"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Arabic.traineddata"
  sha256 "a80454f72df35c6f52550551dd69b8521ea6a62d834396d1c7dce4c35493902e"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Arabic.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Arabic.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Arabic
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Arabic.traineddata"
  end
end
