# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestChiTraVert < Formula
  desc "Best Tesseract OCR data for Chinese (Traditional, Vertical) (chi_tra_vert)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/chi_tra_vert.traineddata"
  sha256 "bbe518f94b9e3852109113507357bfe7e257834d88d2d1ead44178046bcd2181"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "chi_tra_vert.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/chi_tra_vert.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l chi_tra_vert
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/chi_tra_vert.traineddata"
  end
end
