# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestSpa < Formula
  desc "Best Tesseract OCR data for Spanish (spa)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/spa.traineddata"
  sha256 "e2c1ffdad8b30f26c45d4017a9183d3a7f9aa69e59918be4f88b126fac99ab2c"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "spa.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/spa.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l spa
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/spa.traineddata"
  end
end
