# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestFao < Formula
  desc "Best Tesseract OCR data for Faroese (fao)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/fao.traineddata"
  sha256 "7e4f7a4ac23e6379aad2d4aacdf11e1875cd88e35ffc11eb78005e0e470ce962"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "fao.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/fao.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l fao
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/fao.traineddata"
  end
end
