# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestSwe < Formula
  desc "Best Tesseract OCR data for Swedish (swe)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/swe.traineddata"
  sha256 "360303308aa5d4a912ac3b3637691152b7532d9bd6e960639db1affb83db7ea9"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "swe.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/swe.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l swe
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/swe.traineddata"
  end
end
