# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestBel < Formula
  desc "Best Tesseract OCR data for Belarusian (bel)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/bel.traineddata"
  sha256 "f9503249d58dcfe794c3175abf4d21b1cb76c2dac891626fc864f217e0bb9294"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "bel.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/bel.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l bel
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/bel.traineddata"
  end
end
