# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestIku < Formula
  desc "Best Tesseract OCR data for Inuktitut (iku)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/iku.traineddata"
  sha256 "6b65466ef44f8d38e593ecfedaf0434cc24163c108db1a019c68ac174e035905"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "iku.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/iku.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l iku
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/iku.traineddata"
  end
end
