# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestUig < Formula
  desc "Best Tesseract OCR data for Uyghur (uig)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/uig.traineddata"
  sha256 "e379b5ab22ff515ab645efbc2c0a683af96e058a52d29f611b9534ad7c2d824a"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "uig.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/uig.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l uig
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/uig.traineddata"
  end
end
