# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestYid < Formula
  desc "Best Tesseract OCR data for Yiddish (yid)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/yid.traineddata"
  sha256 "086ec92aea9c7016c74b503c3d24906381e7e57cc3f487f12e1784eb2530ba94"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "yid.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/yid.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l yid
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/yid.traineddata"
  end
end
