# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestHun < Formula
  desc "Best Tesseract OCR data for Hungarian (hun)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/hun.traineddata"
  sha256 "08786ad5fe25d502d1cfcdf606ba215f320409a1630109582fa1a38d93b3e32d"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "hun.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/hun.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l hun
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/hun.traineddata"
  end
end
