# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptGeorgian < Formula
  desc "Best Tesseract OCR script data for Georgian"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Georgian.traineddata"
  sha256 "d24244c141354eeb841a487deede0642d06e2271ae6278160955b8a31db2f9e4"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Georgian.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Georgian.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Georgian
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Georgian.traineddata"
  end
end
