# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestAfr < Formula
  desc "Best Tesseract OCR data for Afrikaans (afr)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/afr.traineddata"
  sha256 "6f80b369205a51298a2113c662585d52dfc81bb9331c21845538cec959ebe09a"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "afr.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/afr.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l afr
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/afr.traineddata"
  end
end
