# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestFas < Formula
  desc "Best Tesseract OCR data for Persian (fas)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/fas.traineddata"
  sha256 "99e420969b5ddd2cb135b416316a7ed417c59c4faf9e0d28941348f6448114df"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "fas.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/fas.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l fas
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/fas.traineddata"
  end
end
