# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestDiv < Formula
  desc "Best Tesseract OCR data for Dhivehi (div)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/div.traineddata"
  sha256 "7f923088b173b278ed9d27609fccc9b6571ef7dae11898825d934ed6a2998133"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "div.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/div.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l div
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/div.traineddata"
  end
end
