# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptLao < Formula
  desc "Best Tesseract OCR script data for Lao"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Lao.traineddata"
  sha256 "8a8dd62e8ca2d5a1c579ad6d9aaa45f0d02344dbde36de7b4479ed32ddebf012"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Lao.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Lao.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Lao
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Lao.traineddata"
  end
end
