# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestMkd < Formula
  desc "Best Tesseract OCR data for Macedonian (mkd)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/mkd.traineddata"
  sha256 "be5f0af7a7b7a1a804069bcab83225286d78ce3171c6a1d1587f975b083af299"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "mkd.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/mkd.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l mkd
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/mkd.traineddata"
  end
end
