# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestAze < Formula
  desc "Best Tesseract OCR data for Azerbaijani (aze)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/aze.traineddata"
  sha256 "6f183760f210177cf8c8eb6bf4821a8e488a4137ad06549ae483266c7cfd455f"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "aze.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/aze.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l aze
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/aze.traineddata"
  end
end
