# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestKaz < Formula
  desc "Best Tesseract OCR data for Kazakh (kaz)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/kaz.traineddata"
  sha256 "34cbd9204b1ff3cc813d50b29e3c0ae3752bcc201f261a4a393ceca3895aea9d"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "kaz.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/kaz.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l kaz
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/kaz.traineddata"
  end
end
