# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestAsm < Formula
  desc "Best Tesseract OCR data for Assamese (asm)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/asm.traineddata"
  sha256 "7ee579ad079e30566e856dfe7fc5ce0724f3625e69025cc88c785237172d9308"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "asm.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/asm.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l asm
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/asm.traineddata"
  end
end
