# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptVietnamese < Formula
  desc "Best Tesseract OCR script data for Vietnamese"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Vietnamese.traineddata"
  sha256 "763c04c791888e912efa4a23b55f795baf371bd953697535b1dc9935045c8fd5"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Vietnamese.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Vietnamese.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Vietnamese
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Vietnamese.traineddata"
  end
end
