# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestNor < Formula
  desc "Best Tesseract OCR data for Norwegian (nor)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/nor.traineddata"
  sha256 "451d52ba1559aa1aecf163ccbfdeced2b9605fbd49480f5e8a53ace29b9eb0e7"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "nor.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/nor.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l nor
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/nor.traineddata"
  end
end
