# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestEng < Formula
  desc "Best Tesseract OCR data for English (eng)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/eng.traineddata"
  sha256 "8280aed0782fe27257a68ea10fe7ef324ca0f8d85bd2fd145d1c2b560bcb66ba"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "eng.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/eng.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l eng
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/eng.traineddata"
  end
end
