# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestJpn < Formula
  desc "Best Tesseract OCR data for Japanese (jpn)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/jpn.traineddata"
  sha256 "36bdf9ac823f5911e624c30d0553e890b8abc7c31a65b3ef14da943658c40b79"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "jpn.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/jpn.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l jpn
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/jpn.traineddata"
  end
end
