# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestBos < Formula
  desc "Best Tesseract OCR data for Bosnian (bos)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/bos.traineddata"
  sha256 "009b938969013ce99793a8c90fa06ff2e5ce3fde8036d2790dc2e782829c06eb"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "bos.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/bos.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l bos
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/bos.traineddata"
  end
end
