# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestDeu < Formula
  desc "Best Tesseract OCR data for German (deu)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/deu.traineddata"
  sha256 "8407331d6aa0229dc927685c01a7938fc5a641d1a9524f74838cdac599f0d06e"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "deu.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/deu.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l deu
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/deu.traineddata"
  end
end
