# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestPus < Formula
  desc "Best Tesseract OCR data for Pashto (pus)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/pus.traineddata"
  sha256 "b5e3ad39342e1b8cedf3b74cb647eeb0858fec74c00aa98703288aef01ebad65"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "pus.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/pus.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l pus
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/pus.traineddata"
  end
end
