# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestFra < Formula
  desc "Best Tesseract OCR data for French (fra)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/fra.traineddata"
  sha256 "907743d98915c91a3906dfbf6e48b97598346698fe53aaa797e1a064ffcac913"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "fra.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/fra.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l fra
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/fra.traineddata"
  end
end
