# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptCyrillic < Formula
  desc "Best Tesseract OCR script data for Cyrillic"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Cyrillic.traineddata"
  sha256 "4ad9e44d219e2c18ac1d7dccc79863408acde090d9875908517606942a951018"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Cyrillic.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Cyrillic.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Cyrillic
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Cyrillic.traineddata"
  end
end
