# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptHangul < Formula
  desc "Best Tesseract OCR script data for Hangul"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Hangul.traineddata"
  sha256 "8bfdf61f86d49812b14e0afdc8e3e67e0b50d02078f50e209f4366558fc4feca"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Hangul.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Hangul.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Hangul
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Hangul.traineddata"
  end
end
