# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestFin < Formula
  desc "Best Tesseract OCR data for Finnish (fin)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/fin.traineddata"
  sha256 "96745dd0900fe997541516863d859616df6120430db546424feae72923828423"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "fin.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/fin.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l fin
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/fin.traineddata"
  end
end
