# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestChiTra < Formula
  desc "Best Tesseract OCR data for Chinese (Traditional) (chi_tra)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/chi_tra.traineddata"
  sha256 "1aa60488574cafa69486d919284f079ca9b68fcc7f6ad8dc1ff1b318dfd97028"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "chi_tra.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/chi_tra.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l chi_tra
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/chi_tra.traineddata"
  end
end
