# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestMri < Formula
  desc "Best Tesseract OCR data for Maori (mri)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/mri.traineddata"
  sha256 "67d322dcc41ca59929236c85393c6ecc644c29feda149fbe2b95adcb4a1b0494"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "mri.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/mri.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l mri
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/mri.traineddata"
  end
end
