# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestCat < Formula
  desc "Best Tesseract OCR data for Catalan (cat)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/cat.traineddata"
  sha256 "dbddfce4cc65e5b127566d85243fe4422ef321f028b74ccf8db5c253f227a61a"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "cat.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/cat.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l cat
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/cat.traineddata"
  end
end
