# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestNld < Formula
  desc "Best Tesseract OCR data for Dutch (nld)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/nld.traineddata"
  sha256 "92e7a1ad4bf8082e268de57c7823316ec024935702c6ed2a1e473b3a071aa733"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "nld.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/nld.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l nld
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/nld.traineddata"
  end
end
