# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestIsl < Formula
  desc "Best Tesseract OCR data for Icelandic (isl)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/isl.traineddata"
  sha256 "b4bf195ce73fa9098ccdf7b8b25ffb7cfb1395346bb3fa1355c40d4bc9e6792a"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "isl.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/isl.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l isl
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/isl.traineddata"
  end
end
