# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestSin < Formula
  desc "Best Tesseract OCR data for Sinhala (sin)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/sin.traineddata"
  sha256 "1d95b36e935c8c12cc890684fad15bd3ad8d904c3a6ffa2fccb81658eabd8454"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "sin.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/sin.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l sin
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/sin.traineddata"
  end
end
