# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestCym < Formula
  desc "Best Tesseract OCR data for Welsh (cym)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/cym.traineddata"
  sha256 "4f45069e33ef9719dab3417dfbcb9cebb87078bf95a614dcc038cf9d7ae1b580"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "cym.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/cym.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l cym
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/cym.traineddata"
  end
end
