# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestJpnVert < Formula
  desc "Best Tesseract OCR data for Japanese (Vertical) (jpn_vert)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/jpn_vert.traineddata"
  sha256 "1258be6eb2a9851f18043234ad18cca13ed32690bfff62b335c898bbea371548"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "jpn_vert.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/jpn_vert.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l jpn_vert
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/jpn_vert.traineddata"
  end
end
