# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestKan < Formula
  desc "Best Tesseract OCR data for Kannada (kan)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/kan.traineddata"
  sha256 "6f195e0f33f0ec5118c97eff777ed70ac453d67c32bf06a43f79dab875f8ebfe"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "kan.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/kan.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l kan
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/kan.traineddata"
  end
end
