# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestTir < Formula
  desc "Best Tesseract OCR data for Tigrinya (tir)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/tir.traineddata"
  sha256 "5322d0ee350c09d58d16b262219e4bfd12ad29424b98f0b347c9595aab1f7e19"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "tir.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/tir.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l tir
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/tir.traineddata"
  end
end
