# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestHrv < Formula
  desc "Best Tesseract OCR data for Croatian (hrv)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/hrv.traineddata"
  sha256 "a46566f0a1442502028bc0c35f043bc1780cc80e8567ec1b1df13d685c47215e"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "hrv.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/hrv.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l hrv
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/hrv.traineddata"
  end
end
