# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestFry < Formula
  desc "Best Tesseract OCR data for Western Frisian (fry)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/fry.traineddata"
  sha256 "da42beb26f975f83c3436f2b5fd4132c9f9c3064fbeffb49ba3870b00fcf8db9"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "fry.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/fry.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l fry
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/fry.traineddata"
  end
end
