# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestTgk < Formula
  desc "Best Tesseract OCR data for Tajik (tgk)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/tgk.traineddata"
  sha256 "cb2f067a5d986713bd0f123f80e843e591cef1295d4af71919118652186f5852"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "tgk.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/tgk.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l tgk
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/tgk.traineddata"
  end
end
