# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestSyr < Formula
  desc "Best Tesseract OCR data for Syriac (syr)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/syr.traineddata"
  sha256 "7642168b7731866d0ec4c74c67780913db4a04583874fcff0078daa8430bd887"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "syr.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/syr.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l syr
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/syr.traineddata"
  end
end
