# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestSnd < Formula
  desc "Best Tesseract OCR data for Sindhi (snd)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/snd.traineddata"
  sha256 "d945fc2f379b6c353bf28bf06d545a9270f6a7d11c05c0c0fb20ed29650ba2e3"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "snd.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/snd.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l snd
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/snd.traineddata"
  end
end
