# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestYor < Formula
  desc "Best Tesseract OCR data for Yoruba (yor)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/yor.traineddata"
  sha256 "3380579148d53533f0ad740b825248959067f83c3b1903c49d11652054339295"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "yor.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/yor.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l yor
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/yor.traineddata"
  end
end
