# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestSrp < Formula
  desc "Best Tesseract OCR data for Serbian (srp)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/srp.traineddata"
  sha256 "b090f9bb22366d9b4b0cb6baa2136c4f75e992ddba01ecb78240896e359e4072"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "srp.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/srp.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l srp
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/srp.traineddata"
  end
end
