# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestEnm < Formula
  desc "Best Tesseract OCR data for English (Middle) (enm)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/enm.traineddata"
  sha256 "934463c845bdf9bfe087038f96a3b1b770d8e5fd6175ef0892066a02b2bd0e52"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "enm.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/enm.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l enm
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/enm.traineddata"
  end
end
