# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestChiSim < Formula
  desc "Best Tesseract OCR data for Chinese (Simplified) (chi_sim)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/chi_sim.traineddata"
  sha256 "4fef2d1306c8e87616d4d3e4c6c67faf5d44be3342290cf8f2f0f6e3aa7e735b"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "chi_sim.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/chi_sim.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l chi_sim
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/chi_sim.traineddata"
  end
end
