# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestKat < Formula
  desc "Best Tesseract OCR data for Georgian (kat)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/kat.traineddata"
  sha256 "557f48b753fdbbee2c77d83bae2542af249f915be6cf80883892a579ea2a81db"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "kat.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/kat.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l kat
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/kat.traineddata"
  end
end
