# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestLav < Formula
  desc "Best Tesseract OCR data for Latvian (lav)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/lav.traineddata"
  sha256 "fc5b602bc21987e09468f9ec5baaef1d1a29e26eb334545531294a0af9407c69"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "lav.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/lav.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l lav
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/lav.traineddata"
  end
end
