# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestRon < Formula
  desc "Best Tesseract OCR data for Romanian (ron)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/ron.traineddata"
  sha256 "93588d7e59a28fad7920db07767345438ee5eeefa3c5f20541dfb9ad083a6d2e"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "ron.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/ron.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l ron
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/ron.traineddata"
  end
end
