# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestTur < Formula
  desc "Best Tesseract OCR data for Turkish (tur)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/tur.traineddata"
  sha256 "e0c3338dc17503dc7d335a507c9ae01b2b46cfd07561171e1e1ac55d85e8e438"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "tur.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/tur.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l tur
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/tur.traineddata"
  end
end
