# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptSyriac < Formula
  desc "Best Tesseract OCR script data for Syriac"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Syriac.traineddata"
  sha256 "840467dbe8c936baa32d87f060b56c5e2054434a58f3c567bbfec4498bb35c06"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Syriac.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Syriac.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Syriac
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Syriac.traineddata"
  end
end
