# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestAzeCyrl < Formula
  desc "Best Tesseract OCR data for Azerbaijani (Cyrillic) (aze_cyrl)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/aze_cyrl.traineddata"
  sha256 "e857ab208c63fe9286add2bea39846793bf80e5cf823b5a3853e35702e35b400"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "aze_cyrl.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/aze_cyrl.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l aze_cyrl
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/aze_cyrl.traineddata"
  end
end
