# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptThaana < Formula
  desc "Best Tesseract OCR script data for Thaana"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Thaana.traineddata"
  sha256 "84f80175c9d20045c683a55887356470bf4759c0058b67069b0bf564b0da571c"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Thaana.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Thaana.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Thaana
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Thaana.traineddata"
  end
end
