# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestMsa < Formula
  desc "Best Tesseract OCR data for Malay (msa)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/msa.traineddata"
  sha256 "2fa693701d2fb3685cf3e0a64bc1bfb97d66a50f93c07b2ebc0ff360ea62621f"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "msa.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/msa.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l msa
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/msa.traineddata"
  end
end
