# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptHans < Formula
  desc "Best Tesseract OCR script data for Han Simplified"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/HanS.traineddata"
  sha256 "3a5291736537b6ed94e7e3064790788eba6deb517d5dd071005b2a2f57aa2339"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "HanS.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/HanS.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/HanS
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/HanS.traineddata"
  end
end
