# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestDzo < Formula
  desc "Best Tesseract OCR data for Dzongkha (dzo)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/dzo.traineddata"
  sha256 "7587d0ee3161ec8a4d939482207eba94fb81ab3c2d80f2b4c4a2c429b8d8b99a"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "dzo.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/dzo.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l dzo
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/dzo.traineddata"
  end
end
