# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestChr < Formula
  desc "Best Tesseract OCR data for Cherokee (chr)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/chr.traineddata"
  sha256 "b3a0da90e7744cfec534cdf2dd85860718f32b5595a07d4b7e49113a89bd0f98"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "chr.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/chr.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l chr
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/chr.traineddata"
  end
end
