# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestBul < Formula
  desc "Best Tesseract OCR data for Bulgarian (bul)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/bul.traineddata"
  sha256 "87322f07ae023d0f61d3c12507f6f1ed22411c00f1b2e722d2e13b723584fad1"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "bul.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/bul.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l bul
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/bul.traineddata"
  end
end
