# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptHangulVert < Formula
  desc "Best Tesseract OCR script data for Hangul (Vertical)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Hangul_vert.traineddata"
  sha256 "3f2d7b201a3485154654431fff292ba0dca8fe860c479a739a91de52da7d0642"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Hangul_vert.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Hangul_vert.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Hangul_vert
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Hangul_vert.traineddata"
  end
end
