# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestBen < Formula
  desc "Best Tesseract OCR data for Bengali (ben)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/ben.traineddata"
  sha256 "1cd0129288d1f74f6661c35e638e487bd146a66bb732ecd9e011e48dcb0df623"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "ben.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/ben.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l ben
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/ben.traineddata"
  end
end
