# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestUrd < Formula
  desc "Best Tesseract OCR data for Urdu (urd)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/urd.traineddata"
  sha256 "65af3f6e50a3c3df15d7b405aab5d467e53433207745c8f5be5b8ff1a58a67c8"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "urd.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/urd.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l urd
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/urd.traineddata"
  end
end
