# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestBod < Formula
  desc "Best Tesseract OCR data for Tibetan (bod)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/bod.traineddata"
  sha256 "7b086e5d13fe9f04b873cfd0f71586717307cbbbe5eefb72a1d7a75d7fcf9da4"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "bod.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/bod.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l bod
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/bod.traineddata"
  end
end
