# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestGle < Formula
  desc "Best Tesseract OCR data for Irish (gle)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/gle.traineddata"
  sha256 "f8e198fb8243be9b167fe49c90794bf5ed3c239e67a79de5e22306e43b0aaa55"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "gle.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/gle.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l gle
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/gle.traineddata"
  end
end
