# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptEthiopic < Formula
  desc "Best Tesseract OCR script data for Ethiopic"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Ethiopic.traineddata"
  sha256 "a49a13365360d58b1ef9097f0d6dd1d0928faeffe13218289dc83f77002d1ae6"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Ethiopic.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Ethiopic.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Ethiopic
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Ethiopic.traineddata"
  end
end
