# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestPol < Formula
  desc "Best Tesseract OCR data for Polish (pol)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/pol.traineddata"
  sha256 "e80cc4cefbdface06e9223f43f089556b9dcf104020fbc0a200f6863c57d4405"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "pol.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/pol.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l pol
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/pol.traineddata"
  end
end
