# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestEst < Formula
  desc "Best Tesseract OCR data for Estonian (est)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/est.traineddata"
  sha256 "d7bfea95a53c302b378655314adc366e294a5a95d7d611911fce5e66318d3ccd"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "est.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/est.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l est
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/est.traineddata"
  end
end
