# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptBengali < Formula
  desc "Best Tesseract OCR script data for Bengali"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Bengali.traineddata"
  sha256 "16572fe14fec083b480a844fb1679ee581e1d8517b5d8c36d0bba2e09d720d6a"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Bengali.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Bengali.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Bengali
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Bengali.traineddata"
  end
end
