# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptHantVert < Formula
  desc "Best Tesseract OCR script data for Han Traditional (Vertical)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/HanT_vert.traineddata"
  sha256 "4f4428a9e2368c5d58275f893dee60fafa1e8b8d96d9e16ee578f96387b1fca2"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "HanT_vert.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/HanT_vert.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/HanT_vert
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/HanT_vert.traineddata"
  end
end
