# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestUkr < Formula
  desc "Best Tesseract OCR data for Ukrainian (ukr)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/ukr.traineddata"
  sha256 "1277f6e3b6f707063a92d40e7678e7f57154e8414e328e340be9ee9275eea9c8"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "ukr.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/ukr.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l ukr
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/ukr.traineddata"
  end
end
