# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestChiSimVert < Formula
  desc "Best Tesseract OCR data for Chinese (Simplified, Vertical) (chi_sim_vert)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/chi_sim_vert.traineddata"
  sha256 "ea672a78157199c333aa12ec4e74550077689b545df5fc770903716850c8b2e5"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "chi_sim_vert.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/chi_sim_vert.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l chi_sim_vert
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/chi_sim_vert.traineddata"
  end
end
