# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestOri < Formula
  desc "Best Tesseract OCR data for Oriya (ori)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/ori.traineddata"
  sha256 "90dfe91cea0b25cf96b2bb283905ba1452534776df3f00d47530939d56339534"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "ori.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/ori.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l ori
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/ori.traineddata"
  end
end
