# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestPan < Formula
  desc "Best Tesseract OCR data for Panjabi (pan)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/pan.traineddata"
  sha256 "6971b1f5c4094da3d73cd13bc79429de912a31919330324556a26e3b4802b905"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "pan.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/pan.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l pan
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/pan.traineddata"
  end
end
