# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestGrc < Formula
  desc "Best Tesseract OCR data for Ancient Greek (grc)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/grc.traineddata"
  sha256 "dfc9bda286cd9d8755b1832e5731a5425d1cf0803393a5fa6dee078466178cf1"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "grc.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/grc.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l grc
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/grc.traineddata"
  end
end
