# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestScriptTibetan < Formula
  desc "Best Tesseract OCR script data for Tibetan"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/script/Tibetan.traineddata"
  sha256 "1958f3d07fdef1f97c0c5ef61a24bc422c5be0bd57193852befd93eb228c05c5"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best/script").install "Tibetan.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/script/Tibetan.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l script/Tibetan
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/script/Tibetan.traineddata"
  end
end
