# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestHin < Formula
  desc "Best Tesseract OCR data for Hindi (hin)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/hin.traineddata"
  sha256 "bd2e65a2184af08a167b0be2439e91fa5edbc4394399ca2f692b843ae26e78d6"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "hin.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/hin.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l hin
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/hin.traineddata"
  end
end
