# frozen_string_literal: true

# This file is auto-generated by scripts/generate-tessdata-formulas.rb.
# Do not edit by hand — regenerate from the manifest instead.

class TessdataBestCeb < Formula
  desc "Best Tesseract OCR data for Cebuano (ceb)"
  homepage "https://github.com/tesseract-ocr/tessdata_best"
  url "https://github.com/tesseract-ocr/tessdata_best/raw/4.1.0/ceb.traineddata"
  sha256 "3ae6bf43f11a5c6a1656f23d8c89adc8c0c641a2ae0a4963bbbbbb6e7b177eff"
  license "Apache-2.0"

  depends_on "tesseract"

  def install
    (share/"tessdata_best").install "ceb.traineddata"
  end

  def caveats
    <<~EOS
      Modèle installé dans :
        #{share}/tessdata_best/ceb.traineddata

      Pour l'utiliser avec Tesseract :
        export TESSDATA_PREFIX="#{share}/tessdata_best"
        tesseract image.png out -l ceb
    EOS
  end

  test do
    assert_path_exists share/"tessdata_best/ceb.traineddata"
  end
end
