#!/usr/bin/env ruby
# frozen_string_literal: true

# Génère les formules Homebrew tessdata-best-<code> et la méta-formule
# tessdata-best-all à partir d'un manifeste TSV.
#
# Format du manifeste (tessdata-best-manifest.tsv) :
#   # tag=<TAG>           ← première ligne, en commentaire
#   # license_sha=<SHA>   ← SHA du fichier LICENSE en amont (pour la méta-formule)
#   path<TAB>size<TAB>sha256
#   ...
#
# Usage : ruby scripts/generate-tessdata-formulas.rb

require "fileutils"

TAP_ROOT     = File.expand_path("..", __dir__).freeze
SCRIPT_DIR   = __dir__.freeze
MANIFEST     = File.join(SCRIPT_DIR, "tessdata-best-manifest.tsv").freeze
FORMULA_DIR  = File.join(TAP_ROOT, "Formula").freeze
RAW_BASE     = "https://github.com/tesseract-ocr/tessdata_best/raw"
HOMEPAGE     = "https://github.com/tesseract-ocr/tessdata_best"

require_relative "tessdata-best-langs"

# --- Helpers ----------------------------------------------------------------

def parse_manifest(path)
  tag = nil
  license_sha = nil
  files = []
  File.foreach(path) do |line|
    line = line.chomp
    next if line.empty?

    if line.start_with?("#")
      tag         = Regexp.last_match(1) if line =~ /\Atag=(\S+)/i || line =~ /\A#\s*tag=(\S+)/i
      license_sha = Regexp.last_match(1) if line =~ /\Alicense_sha=(\S+)/i || line =~ /\A#\s*license_sha=(\S+)/i
      next
    end

    parts = line.split("\t")
    raise "Ligne manifeste invalide : #{line.inspect}" if parts.size != 3

    files << { path: parts[0], size: parts[1].to_i, sha256: parts[2] }
  end

  raise "tag manquant dans #{path}" if tag.nil?
  raise "license_sha manquant dans #{path}" if license_sha.nil?
  raise "aucun fichier dans #{path}" if files.empty?

  [tag, license_sha, files]
end

# "fra.traineddata"          -> "tessdata-best-fra"
# "script/Latin.traineddata" -> "tessdata-best-script-latin"
def formula_name(file_path)
  base = file_path.delete_suffix(".traineddata").downcase.gsub(%r{[/_]}, "-")
  "tessdata-best-#{base}"
end

# "tessdata-best-script-hans-vert" -> "TessdataBestScriptHansVert"
def class_name(name)
  name.split("-").map(&:capitalize).join
end

# Sous-dossier d'install relatif à share :
#   "fra.traineddata"          -> "tessdata_best"
#   "script/Latin.traineddata" -> "tessdata_best/script"
def install_subdir(file_path)
  dir = File.dirname(file_path)
  (dir == ".") ? "tessdata_best" : "tessdata_best/#{dir}"
end

# Description courte (≤ 80 chars), avec nom humain si connu.
# Doit commencer par une majuscule (FormulaAudit/Desc).
def description_for(file_path)
  basename = File.basename(file_path, ".traineddata")
  if file_path.start_with?("script/")
    human = SCRIPT_NAMES[basename] || basename
    "Best Tesseract OCR script data for #{human}"
  else
    human = LANG_NAMES[basename]
    if human
      desc = "Best Tesseract OCR data for #{human} (#{basename})"
      desc = "Best Tesseract OCR data: #{human}" if desc.length > 80
      desc
    else
      "Best Tesseract OCR data: #{basename}"
    end
  end
end

# --- Templates --------------------------------------------------------------

def render_data_formula(file, tag)
  name      = formula_name(file[:path])
  klass     = class_name(name)
  desc      = description_for(file[:path])
  subdir    = install_subdir(file[:path])
  basename  = File.basename(file[:path])
  url       = "#{RAW_BASE}/#{tag}/#{file[:path]}"
  rel_lang  = file[:path].delete_suffix(".traineddata")

  <<~RUBY
    # frozen_string_literal: true

    # This file is auto-generated by scripts/generate-tessdata-formulas.rb.
    # Do not edit by hand — regenerate from the manifest instead.

    class #{klass} < Formula
      desc "#{desc}"
      homepage "#{HOMEPAGE}"
      url "#{url}"
      sha256 "#{file[:sha256]}"
      license "Apache-2.0"

      depends_on "tesseract"

      def install
        (share/"#{subdir}").install "#{basename}"
      end

      def caveats
        <<~EOS
          Modèle installé dans :
            \#{share}/tessdata_best/#{file[:path]}

          Pour l'utiliser avec Tesseract :
            export TESSDATA_PREFIX="\#{share}/tessdata_best"
            tesseract image.png out -l #{rel_lang}
        EOS
      end

      test do
        assert_path_exists share/"#{subdir}/#{basename}"
      end
    end
  RUBY
end

def render_meta_formula(deps, tag, license_sha)
  url = "#{RAW_BASE}/#{tag}/LICENSE"
  deps_block = deps.sort.map { |d| "  depends_on \"#{d}\"" }.join("\n")

  <<~RUBY
    # frozen_string_literal: true

    # This file is auto-generated by scripts/generate-tessdata-formulas.rb.
    # Do not edit by hand — regenerate from the manifest instead.

    class TessdataBestAll < Formula
      desc "All tessdata_best language and script models for Tesseract OCR"
      homepage "#{HOMEPAGE}"
      url "#{url}"
      sha256 "#{license_sha}"
      license "Apache-2.0"

    #{deps_block}

      def install
        pkgshare.install "LICENSE"
      end

      def caveats
        <<~EOS
          Toutes les langues et scripts tessdata_best ont été installés dans :
            \#{HOMEBREW_PREFIX}/share/tessdata_best/

          Pour les utiliser avec Tesseract :
            export TESSDATA_PREFIX="\#{HOMEBREW_PREFIX}/share/tessdata_best"
            tesseract --list-langs

          Désinstallation : `brew uninstall tessdata-best-all` ne retire pas
          les langues. Utilisez `brew uninstall $(brew deps tessdata-best-all)`
          pour tout retirer.
        EOS
      end

      test do
        assert_path_exists pkgshare/"LICENSE"
        assert_path_exists share/"tessdata_best/eng.traineddata"
        assert_path_exists share/"tessdata_best/osd.traineddata"
      end
    end
  RUBY
end

# --- Main -------------------------------------------------------------------

tag, license_sha, files = parse_manifest(MANIFEST)

FileUtils.mkdir_p(FORMULA_DIR)

# On supprime les anciennes formules tessdata-best-* avant régénération
# pour ne pas laisser de fichiers obsolètes (ex. langue retirée upstream).
Dir.glob(File.join(FORMULA_DIR, "tessdata-best-*.rb")).each do |f|
  File.delete(f)
end

names = []
files.each do |file|
  name = formula_name(file[:path])
  names << name
  out = File.join(FORMULA_DIR, "#{name}.rb")
  File.write(out, render_data_formula(file, tag))
end

meta_out = File.join(FORMULA_DIR, "tessdata-best-all.rb")
File.write(meta_out, render_meta_formula(names, tag, license_sha))

puts "OK : #{names.size} formules générées + tessdata-best-all (tag #{tag})"
